### ISSUE TITLE
learn-recipes: true

### ISSUE THREAD

**Issue by sikskUnII** [DutchJelly/CraftEnhance#32]
[Server thread/ERROR]: Could not pass event PlayerJoinEvent to CraftEnhance v2.4.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.discoverRecipe(Lorg/bukkit/NamespacedKey;)Z
	at com.dutchjelly.bukkitadapter.Adapter.DiscoverRecipes(Adapter.java:126) ~[?:?]
	at com.dutchjelly.craftenhance.crafthandling.RecipeLoader.onJoin(RecipeLoader.java:29) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[SkyBlock.jar:git-Spigot-dcd1643-e60fc34]
	... 14 more

**Comment by DutchJelly** [comment]
Thanks for reporting this, and sorry that I'm late with replying.

I'll be looking to fix this in version 2.4.3, but I cannot promise that this'll be completely fixed. The learn recipes part is pretty tricky and probably needs some recoding.

**Comment by broken1arrow** [comment]
> [Server thread/ERROR]: Could not pass event PlayerJoinEvent to CraftEnhance v2.4.2 org.bukkit.event.EventException: null at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [SkyBlock.jar:git-Spigot-dcd1643-e60fc34] at java.lang.Thread.run(Unknown Source) [?:1.8.0_51] Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.discoverRecipe(Lorg/bukkit/NamespacedKey;)Z at com.dutchjelly.bukkitadapter.Adapter.DiscoverRecipes(Adapter.java:126) ~[?:?] at com.dutchjelly.craftenhance.crafthandling.RecipeLoader.onJoin(RecipeLoader.java:29) ~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[SkyBlock.jar:git-Spigot-dcd1643-e60fc34] ... 14 more

You has not update this issue. So think is solved. I think is better you open new issue, if you get problems in current latest update.

**Comment by broken1arrow** [comment]
close this issue.
