### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by dogi-dogi** [DutchJelly/CraftEnhance#41]
[16:07:28 INFO]: YAshaw issued server command: /ceh createrecipe test
[16:07:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ceh' in plugin CraftEnhance v2.4.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_301]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_301]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: com.dutchjelly.craftenhance.exceptions.ConfigError: Cannot find template of EditorTypeSelector
        at com.dutchjelly.craftenhance.files.GuiTemplatesFile.getTemplate(GuiTemplatesFile.java:72) ~[?:?]
        at com.dutchjelly.craftenhance.commands.ceh.CreateRecipeCmd.handlePlayerCommand(CreateRecipeCmd.java:53) ~[?:?]
        at com.dutchjelly.craftenhance.commandhandling.CustomCmdHandler.handleCommand(CustomCmdHandler.java:91) ~[?:?]
        at com.dutchjelly.craftenhance.CraftEnhance.onCommand(CraftEnhance.java:156) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Paper.jar:git-Paper-1618]
        ... 15 more

**Comment by DutchJelly** [comment]
To find out why this is caused, I'll need the startup log. What you could try to do to solve this is deleting your guiTemplates.yml file, so it'll generate a fresh updated one.

**Comment by broken1arrow** [comment]
I will say this issue also is fixed.
